# Generated by Django 2.0.6 on 2018-06-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
            ],
        ),
    ]
