# Generated by Django 2.0.6 on 2018-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdata',
            name='timeIn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pastdata',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
