# Generated by Django 2.0.6 on 2018-06-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20180602_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=1000)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.section')),
            ],
        ),
    ]
