# Generated by Django 2.0.6 on 2018-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20180602_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=13.456781),
            preserve_default=False,
        ),
    ]
