# Generated by Django 2.0.6 on 2018-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_place_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
