# Generated by Django 2.0.6 on 2018-06-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportType', to='tracking.type'),
        ),
    ]
