# Generated by Django 2.0.6 on 2018-06-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20180602_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='subSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=200)),
                ('order', models.IntegerField()),
                ('endPlace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subSectionEnd', to='tracking.place')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insideSection', to='tracking.section')),
                ('startPlace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subSectionStart', to='tracking.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subTransportType', to='tracking.type')),
            ],
        ),
    ]
