# Generated by Django 2.0.6 on 2018-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
