# Generated by Django 2.0.6 on 2018-06-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_place_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_in_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='endPlace',
        ),
        migrations.RemoveField(
            model_name='section',
            name='startPlace',
        ),
        migrations.AddField(
            model_name='place',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.section'),
        ),
        migrations.AddField(
            model_name='place',
            name='position_in_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.position_in_section'),
        ),
    ]
