# Generated by Django 2.0.6 on 2018-06-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20180606_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='order',
        ),
    ]
