# Generated by Django 2.0.6 on 2018-06-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_remove_place_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='position_in_section',
        ),
        migrations.RemoveField(
            model_name='place',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endPlace', to='tracking.place'),
        ),
        migrations.AddField(
            model_name='section',
            name='middle',
            field=models.ManyToManyField(blank=True, related_name='middlePlace', to='tracking.place'),
        ),
        migrations.AddField(
            model_name='section',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startPlace', to='tracking.place'),
        ),
        migrations.DeleteModel(
            name='position_in_section',
        ),
    ]
