# Generated by Django 2.0.6 on 2018-06-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20180606_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='place2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='middle',
            new_name='waypoints',
        ),
        migrations.AddField(
            model_name='place2',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.section'),
        ),
    ]
