# Generated by Django 2.0.6 on 2018-06-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20180606_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='startEndPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='place2',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='end',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start',
        ),
        migrations.RemoveField(
            model_name='section',
            name='waypoints',
        ),
        migrations.AddField(
            model_name='place',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.section'),
        ),
        migrations.DeleteModel(
            name='place2',
        ),
        migrations.AddField(
            model_name='place',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.startEndPlace'),
        ),
        migrations.AddField(
            model_name='section',
            name='endPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='tracking.startEndPlace'),
        ),
        migrations.AddField(
            model_name='section',
            name='startPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='tracking.startEndPlace'),
        ),
    ]
