# Generated by Django 2.0.6 on 2018-06-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20180606_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place',
        ),
        migrations.AlterField(
            model_name='section',
            name='endPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='tracking.place'),
        ),
        migrations.AlterField(
            model_name='section',
            name='startPlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='tracking.place'),
        ),
        migrations.DeleteModel(
            name='startEndPlace',
        ),
    ]
