# Generated by Django 2.0.6 on 2018-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20180607_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
