# Generated by Django 2.0.6 on 2018-06-12 12:12

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
            preserve_default=False,
        ),
    ]
