# Generated by Django 2.0.6 on 2018-06-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_meetup_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='section',
        ),
        migrations.AddField(
            model_name='place',
            name='section',
            field=models.ManyToManyField(blank=True, to='tracking.section'),
        ),
    ]
