# Generated by Django 2.0.6 on 2018-06-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20180617_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='section',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AlterField(
            model_name='meetup',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetUpPlace', to='tracking.place'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postPlace', to='tracking.place'),
        ),
    ]
