# Generated by Django 2.0.6 on 2018-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_auto_20180620_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdata',
            name='deltaT',
            field=models.FloatField(default=0),
        ),
    ]
