# Generated by Django 2.0.6 on 2018-06-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_pastdata_deltat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastdata',
            old_name='deistanceGoogle',
            new_name='distanceGoogle',
        ),
    ]
