# Generated by Django 2.0.6 on 2018-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_auto_20180620_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdata',
            name='totalDistance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
