# Generated by Django 2.0.6 on 2018-06-27 17:25

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_post_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=colorful.fields.RGBColorField(default='#004080'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
