# Generated by Django 2.0.6 on 2018-06-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0029_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='color',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
    ]
