# Generated by Django 2.0.6 on 2018-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0031_pastdata_lastgettime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdata',
            name='elevation',
            field=models.FloatField(default=0),
        ),
    ]
