# Generated by Django 2.0.6 on 2018-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0032_pastdata_elevation'),
    ]

    operations = [
        migrations.CreateModel(
            name='resolved_coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='endPlace',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='startPlace',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='type',
        ),
        migrations.DeleteModel(
            name='subSection',
        ),
    ]
