# Generated by Django 2.0.6 on 2018-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0034_capped_resolved_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdata',
            name='totalElevation',
            field=models.FloatField(default=0, null=True),
        ),
    ]
