# Generated by Django 2.0.6 on 2018-07-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0035_pastdata_totalelevation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='show',
        ),
    ]
